### ISSUE TITLE
1.641 build marked as failed by chocolatey

### ISSUE THREAD

**Issue by mrlowe** [cbadke/chocolateypackages#4]
Hello, I'm about to install jenkins via chocolatey, but the page in the chocolatey gallery says build 1.641 is breaking (red light). 

https://chocolatey.org/packages/jenkins

Is this a known issue?

**Comment by cbadke** [comment]
Yeah it looks like the automated test may have had a corrupted download or something. I've uploaded a new package for 1.643. We'll see if that makes it through the gauntlet.

**Comment by cbadke** [comment]
1.643 passed the automated testing. Go for it!

**Comment by mrlowe** [comment]
Worked like a charm, thanks. =)
